name: "cron"

on:
    schedule:
      - cron: "*/5 * * * *"
    workflow_dispatch:


env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
  REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
  REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
  REDDIT_PASSWORDL: ${{ secrets.REDDIT_PASSWORD }}
  REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
  SOCIAL_SEARCH_TABLE_NAME: ${{ secrets.SOCIAL_SEARCH_TABLE_NAME }}
  BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}   
  BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }} 

jobs:
  grass:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 

    - name: Install grass
      uses: jaxxstorm/action-install-gh-release@master
      with:
        repo: jaxxstorm/grass

    - name: Run grass
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        SOCIAL_SEARCH_TABLE_NAME: ${{ secrets.SOCIAL_SEARCH_TABLE_NAME }}
        BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}   
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }} 
      run: grass --db=dynamodb --keyword=tailscale --bot=print --bot=discord --searchers=reddit --searchers=hackernews --searchers=bluesky

    
    
        